// Generated by https://quicktype.io

export interface MenuResturant {
  dia: string;
  comidas: Comida[];
}

export interface Comida {
  id: string;
  tipo: string;
  plato: string;
  descripcion: string;
  imagen: string;
  precio: number;
}
