// Generated by https://quicktype.io

export interface MenuResturant {
  dia?: string;
  comidas?: Comida[];
  nombre?: string;
  menu?: Comida[];
}

export interface Comida {
  tipo: string;
  plato: string;
  descripcion: string;
  imagen: string;
}
